package cn.tofly.mis.waterusermanager.data.local.gendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TB_TEST".
*/
public class TbTestDao extends AbstractDao<TbTest, Long> {

    public static final String TABLENAME = "TB_TEST";

    /**
     * Properties of entity TbTest.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property TestId = new Property(0, Long.class, "testId", true, "TEST_ID");
        public final static Property Content = new Property(1, String.class, "content", false, "CONTENT");
    };


    public TbTestDao(DaoConfig config) {
        super(config);
    }
    
    public TbTestDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TB_TEST\" (" + //
                "\"TEST_ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: testId
                "\"CONTENT\" TEXT);"); // 1: content
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TB_TEST\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TbTest entity) {
        stmt.clearBindings();
 
        Long testId = entity.getTestId();
        if (testId != null) {
            stmt.bindLong(1, testId);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(2, content);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TbTest readEntity(Cursor cursor, int offset) {
        TbTest entity = new TbTest( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // testId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // content
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TbTest entity, int offset) {
        entity.setTestId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setContent(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TbTest entity, long rowId) {
        entity.setTestId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TbTest entity) {
        if(entity != null) {
            return entity.getTestId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
