package cn.tofly.mis.gasusermanager;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import cn.tofly.mis.gasusermanager.TbTest;

import cn.tofly.mis.gasusermanager.TbTestDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tbTestDaoConfig;

    private final TbTestDao tbTestDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tbTestDaoConfig = daoConfigMap.get(TbTestDao.class).clone();
        tbTestDaoConfig.initIdentityScope(type);

        tbTestDao = new TbTestDao(tbTestDaoConfig, this);

        registerDao(TbTest.class, tbTestDao);
    }
    
    public void clear() {
        tbTestDaoConfig.getIdentityScope().clear();
    }

    public TbTestDao getTbTestDao() {
        return tbTestDao;
    }

}
