package cn.tofly.mis.gasusermanager;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TB_TEST".
 */
public class TbTest {

    private Long testId;
    private String content;

    public TbTest() {
    }

    public TbTest(Long testId) {
        this.testId = testId;
    }

    public TbTest(Long testId, String content) {
        this.testId = testId;
        this.content = content;
    }

    public Long getTestId() {
        return testId;
    }

    public void setTestId(Long testId) {
        this.testId = testId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

}
